language: ruby
rvm:
- 2.4.2
deploy:
  provider: heroku
  api_key:
    secure: VOfIE5I4xeFqUkaoYpwpyRMYTr49FSm3/aNBdyxqOZxh7OdijBWBBE290AgIqXfmSLojvwXpk6ZZg8RTjtmteYOmh8OEWFjnharFAZumW1JV1XME5Rbokz8JKS/cEGmi6aMIzfEIPKZE7sRY7HrLv6HujNx7Isn2yehQjfTK8LQJ0o0oBln3yknisqjMJwsZdN0FiAmfyV4b5fXKhBMXjEN6j7ii0vTDDZMLbCW9VWAztvZfuPuYyeCooXlVQTzfViPVFaPOynkJPwxuFMbyVFQ5rR2OeK4K624mgcogAx0SCyEoVEeI3us+jW3GNiUqdn2eq3X6S80EfVlhvg3COC5sl0667HgTlOqYnYeoFbU7s0SBk6h3r8iq1I2/rao8uU/xJm8wLJxehGojZASXVoIH08TSGW6RL7+JoLWux7W4CbKaxtkhipxOR3HAkFRx7G5XtOLH84BTxps4jCNog8Xj+b5EjLoI00MV49pDRn75IrIH0Y/eCDPPsU2TME7G8tKUpJXqxutfPpkS51dC859mI7ds5lSLR+pPm8k+wV3hCW5nJzT2lyFXUOluneplLysnWcNkJafecL94ryH1J691cVy5vB1UH0O2cq14A4Q3i/ikt6Ks1LkQiORLpmpZLqynFK6HvtYeZzthJkySakL/C0cA2/WGPDq15Fi9EOs=
  app: reactive-heroku-app
  on:
    repo: AlexMiasoiedov/reactive_heroku
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
