# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffe3cfadf5d9f8e621ad0204ef3597c70a60a0fe0da0d2f24e682004bce0574c1193a5613c6ed402e7415e6a74b9938508a5d826283dcc72ebd26152b82e3e8d

test:
  secret_key_base: 5076f3b6e0aaa4d8466215c3664d7f8dcaee34ab5c792aa082e32afeedfd8b98a49ffff542e711020b4338a25b830054c8c4162b6a16e8971017e7c93ec13adb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
